from .. import chromatogram as chromatogram, spec as spec
from ..utils.GSGR import GSGR as GSGR
from _typeshed import Incomplete

class IndexedGzip:
    path: Incomplete
    file_handler: Incomplete
    offset_dict: Incomplete
    def __init__(self, path, encoding) -> None: ...
    def __del__(self) -> None: ...
    def read(self, size: int = -1): ...
    def __getitem__(self, identifier): ...
    def close(self) -> None: ...
