from .. import chromatogram as chromatogram, regex_patterns as regex_patterns, spec as spec
from _typeshed import Incomplete

class StandardMzml:
    index_regex: Incomplete
    path: Incomplete
    file_handler: Incomplete
    offset_dict: Incomplete
    spec_open: Incomplete
    spec_close: Incomplete
    seek_list: Incomplete
    def __init__(self, path, encoding, build_index_from_scratch: bool = False, index_regex: Incomplete | None = None) -> None: ...
    def get_binary_file_handler(self): ...
    def get_file_handler(self, encoding): ...
    def __getitem__(self, identifier): ...
    def read(self, size: int = -1): ...
    def close(self) -> None: ...
