from .. import chromatogram as chromatogram, regex_patterns as regex_patterns, spec as spec
from _typeshed import Incomplete

class StandardGzip:
    path: Incomplete
    file_handler: Incomplete
    offset_dict: Incomplete
    def __init__(self, path, encoding) -> None: ...
    def close(self) -> None: ...
    def read(self, size: int = -1): ...
    def __getitem__(self, identifier): ...
