from _typeshed import Incomplete

class GSGR:
    file_in: Incomplete
    filename: Incomplete
    magic_bytes: bytes
    indexed: bool
    random_access: bool
    ascii_file: bool
    fname: Incomplete
    def __init__(self, file: Incomplete | None = None) -> None: ...
    def __del__(self) -> None: ...
    def seek(self, offset) -> None: ...
    def read_block(self, index): ...
    def read(self, size: int = -1): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def close(self) -> None: ...
