from _typeshed import Incomplete

class GSGW:
    Lock: bool
    file_name: Incomplete
    max_idx_num: Incomplete
    max_idx_len: Incomplete
    max_offset_len: Incomplete
    generic_header: Incomplete
    index: Incomplete
    first_header_set: bool
    index_magic_bytes: Incomplete
    crc32: int
    isize: int
    comp_str: Incomplete
    def __init__(self, file: Incomplete | None = None, max_idx: int = 10000, max_idx_len: int = 8, max_offset_len: int = 8, output_path: str = './test.dat.igzip', comp_str: int = -1) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...
    @property
    def file_out(self): ...
    @property
    def encoding(self): ...
    @encoding.setter
    def encoding(self, encoding) -> None: ...
    def add_data(self, data, identifier): ...
    def write_index(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
