from _typeshed import Incomplete
from pymzml import chromatogram as chromatogram, spec as spec
from pymzml.run import Reader as Reader

def create_database_from_file(db_name, file_path): ...

class SQLiteDatabase:
    cursor: Incomplete
    def __init__(self, path) -> None: ...
    def __getitem__(self, key): ...
    def get_spectrum_count(self): ...
    def read(self, size: int = -1): ...
