from pymzml.utils.GSGW import GSGW as GSGW

def index_gzip(pathIn, pathOut, max_idx: int = 10000, idx_len: int = 8, verbose: bool = False, comp_str: int = -1) -> None: ...
def index(pathIn, pathOut, max_idx: int = 10000, idx_len: int = 8, verbose: bool = False, comp_str: int = -1) -> None: ...
def make_obo_mapping(obo, reversed: bool = False): ...
