from .msdata import MsData as MsData
from .obo import OboTranslator as OboTranslator
from _typeshed import Incomplete

class Chromatogram(MsData):
    element: Incomplete
    noise_level_estimate: Incomplete
    obo_translator: Incomplete
    ns: Incomplete
    def __init__(self, element, measured_precision: float = 5e-06, *, obo_version: Incomplete | None = None) -> None: ...
    @property
    def ID(self): ...
    @property
    def mz(self): ...
    @property
    def time(self): ...
    @property
    def i(self): ...
    @property
    def profile(self): ...
    @profile.setter
    def profile(self, tuple_list): ...
    def peaks(self): ...
    @property
    def chromatogram_type(self): ...
    @property
    def polarity(self): ...
    @property
    def precursor_mz(self): ...
    @property
    def product_mz(self): ...
    def get_chromatogram_properties(self): ...
