from _typeshed import Incomplete

class MSNumpress:
    is_little_endian: Incomplete
    Filler: Incomplete
    data_state: str
    def __init__(self, data: Incomplete | None = None) -> None: ...
    @property
    def decoded_data(self): ...
    @decoded_data.setter
    def decoded_data(self, data) -> None: ...
    @property
    def encoded_data(self): ...
    @encoded_data.setter
    def encoded_data(self, data) -> None: ...
    def encode_linear(self): ...
    def decode_linear(self): ...
    def encode_pic(self): ...
    def decode_pic(self): ...
    fixed_point: Incomplete
    def encode_slof(self): ...
    def decode_slof(self): ...
    def encode_safe(self) -> None: ...
    def decode_safe(self) -> None: ...
