from .obo import OboTranslator as OboTranslator
from _typeshed import Incomplete

class MsData:
    def get_element_by_name(self, name): ...
    def get_element_by_path(self, hooks): ...
    @property
    def measured_precision(self): ...
    internal_precision: Incomplete
    @measured_precision.setter
    def measured_precision(self, value) -> None: ...
    def to_string(self, encoding: str = 'latin-1', method: str = 'xml'): ...
