from _typeshed import Incomplete

class OboTranslator:
    version: Incomplete
    all_dicts: Incomplete
    id: Incomplete
    name: Incomplete
    definition: Incomplete
    lookups: Incomplete
    MS_tag_regex: Incomplete
    def __init__(self, version: Incomplete | None = None) -> None: ...
    @classmethod
    def from_cache(cls, version): ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, key): ...
    def download_obo(self, version, obo_file) -> None: ...
    def parseOBO(self) -> None: ...
    def add(self, collection_dict) -> None: ...
    def checkOBO(self, idTag, name): ...
