from . import spec
from . import chromatogram as chromatogram, obo as obo, regex_patterns as regex_patterns, spec as spec
from .file_classes.standardMzml import StandardMzml as StandardMzml
from .file_interface import FileInterface as FileInterface
from _typeshed import Incomplete
from io import BytesIO as BytesIO
from typing import Any

class Reader:
    index_regex: Incomplete
    build_index_from_scratch: Incomplete
    skip_chromatogram: Incomplete
    ms_precisions: Incomplete
    info: dict[str, Any]
    path_or_file: Incomplete
    OT: Incomplete
    iter: Incomplete
    def __init__(self, path_or_file, MS_precisions: Incomplete | None = None, obo_version: Incomplete | None = None, build_index_from_scratch: bool = False, skip_chromatogram: bool = True, index_regex: Incomplete | None = None, **kwargs) -> None: ...
    def __next__(self) -> spec.Spectrum | chromatogram.Chromatogram: ...
    def __getitem__(self, identifier) -> spec.Spectrum | chromatogram.Chromatogram: ...
    def __enter__(self) -> Reader: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    @property
    def file_class(self): ...
    def __iter__(self) -> Reader: ...
    def next(self) -> spec.Spectrum | chromatogram.Chromatogram: ...
    def get_spectrum_count(self) -> int | None: ...
    def get_chromatogram_count(self) -> int | None: ...
    def get_spectrum(self, identifier: str | int): ...
    def get_chromatogram(self, identifier: str | int): ...
    def close(self) -> None: ...
    def term_is_a_member(self, tested_term, member_of_term) -> bool: ...
