from . import regex_patterns as regex_patterns
from .decoder import MSDecoder as MSDecoder
from .msdata import MsData as MsData
from .obo import OboTranslator as OboTranslator
from _typeshed import Incomplete

DECON_DEP: bool
PROTON: float
ISOTOPE_AVERAGE_DIFFERENCE: float

class MS_Spectrum(MsData):
    def get_element_by_name(self, name): ...
    def get_element_by_path(self, hooks): ...
    @property
    def measured_precision(self): ...
    internal_precision: Incomplete
    @measured_precision.setter
    def measured_precision(self, value) -> None: ...
    def to_string(self, encoding: str = 'latin-1', method: str = 'xml'): ...

class Spectrum(MsData):
    reprofiled: bool
    obo_translator: Incomplete
    element: Incomplete
    noise_level_estimate: Incomplete
    ns: str
    def __init__(self, element=..., measured_precision: float = 5e-06, *, obo_version: Incomplete | None = None) -> None: ...
    def __del__(self) -> None: ...
    def __add__(self, other_spec): ...
    def __sub__(self, other_spec): ...
    def __mul__(self, value): ...
    def __truediv__(self, value): ...
    def __div__(self, value): ...
    def __getitem__(self, accession): ...
    def get(self, acc, default: Incomplete | None = None): ...
    def __contains__(self, value) -> bool: ...
    @property
    def measured_precision(self): ...
    internal_precision: Incomplete
    @measured_precision.setter
    def measured_precision(self, value) -> None: ...
    @property
    def t_mz_set(self): ...
    @property
    def transformed_mz_with_error(self): ...
    @property
    def transformed_peaks(self): ...
    @property
    def TIC(self): ...
    @property
    def ID(self): ...
    @property
    def id_dict(self): ...
    @property
    def index(self): ...
    @property
    def ms_level(self): ...
    @property
    def scan_time(self): ...
    def scan_time_in_minutes(self): ...
    @property
    def selected_precursors(self): ...
    @property
    def precursors(self): ...
    def remove_precursor_peak(self): ...
    @property
    def mz(self): ...
    @mz.setter
    def mz(self, mz_list) -> None: ...
    @property
    def i(self): ...
    @i.setter
    def i(self, intensity_list) -> None: ...
    def peaks(self, peak_type): ...
    def get_array(self, arr_name): ...
    def get_tims_tof_ion_mobility(self, array_name: str = 'mean inverse reduced ion mobility array'): ...
    def get_all_arrays_in_spec(self, not_found_array: Incomplete | None = None): ...
    def set_peaks(self, peaks, peak_type) -> None: ...
    def reduce(self, peak_type: str = 'raw', mz_range=(None, None)): ...
    def remove_noise(self, mode: str = 'median', noise_level: Incomplete | None = None, signal_to_noise_threshold: float = 1.0): ...
    def estimated_noise_level(self, mode: str = 'median'): ...
    def highest_peaks(self, n): ...
    def ppm2abs(self, value, ppm_value, direction: int = 1, factor: int = 1): ...
    def extreme_values(self, key): ...
    def has_peak(self, mz2find): ...
    def has_overlapping_peak(self, mz): ...
    def similarity_to(self, spec2, round_precision: int = 0): ...
    def transform_mz(self, value): ...
    def deprecation_warning(self, function_name) -> None: ...
    def similarityTo(self, spec2, round_precision: int = 0): ...
    def hasPeak(self, mz): ...
    def extremeValues(self, key): ...
    def transformMZ(self, value): ...
    def hasOverlappingPeak(self, mz): ...
    def highestPeaks(self, n): ...
    def estimatedNoiseLevel(self, mode: str = 'median'): ...
    def removeNoise(self, mode: str = 'median', noiseLevel: Incomplete | None = None): ...
    @property
    def centroidedPeaks(self): ...

class Chromatogram(MsData):
    element: Incomplete
    noise_level_estimate: Incomplete
    obo_translator: Incomplete
    ns: Incomplete
    def __init__(self, element, measured_precision: float = 5e-06, *, obo_version: Incomplete | None = None) -> None: ...
    @property
    def ID(self): ...
    @property
    def mz(self): ...
    @property
    def time(self): ...
    @property
    def i(self): ...
    @property
    def profile(self): ...
    @profile.setter
    def profile(self, tuple_list): ...
    def peaks(self): ...
